services:
  - type: web
    name: ahli-platform
    env: python
    repo: https://github.com/xmansx1/ahali-platform
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: u)vypmxs+0+93ckk!z$@-qu9fv%#x9*3!a(dq)lp8*09$z@y8l
      - key: DEBUG
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        value: dvptglfs2
      - key: CLOUDINARY_API_KEY
        value: 997257163374881
      - key: CLOUDINARY_API_SECRET
        value: u5XPED3CQa2gd7PyHuEaw7BFsbY
      - key: ALLOWED_HOSTS
        value: render.com,.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: DATABASE_URL
        fromDatabase:
          name: ahli-db
          property: connectionString
    