# Generated by Django 5.2.4 on 2025-07-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('text', models.TextField(blank=True, verbose_name='نص الإعلان')),
                ('link', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='صورة الإعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
