# Generated by Django 5.2.4 on 2025-07-17 14:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة الإعلان'),
        ),
    ]
