# Generated by Django 5.2.4 on 2025-07-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('content', models.TextField(help_text='يمكنك استخدام HTML مثل <br> للفواصل', verbose_name='المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نافذة منبثقة',
                'verbose_name_plural': 'النوافذ المنبثقة',
            },
        ),
        migrations.CreateModel(
            name='WelcomePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرسالة')),
                ('message', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
