# Generated by Django 5.2.4 on 2025-07-19 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_popupmessage_welcomepopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة'),
        ),
    ]
