# Generated by Django 5.2.4 on 2025-07-19 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_popupmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='popupmessage',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البداية'),
        ),
    ]
