# Generated by Django 5.2.4 on 2025-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_popupmessage_end_date_popupmessage_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepopup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popups/', verbose_name='الصورة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='welcomepopup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='welcomepopup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
    ]
