# Generated by Django 5.2.4 on 2025-07-20 14:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_welcomepopup_image_alter_welcomepopup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomepopup',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة (اختياري)'),
        ),
    ]
