# Generated by Django 5.2.4 on 2025-07-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='اسم المتجر')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الجوال')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('store_type', models.CharField(choices=[('grocery', 'بقالة'), ('pharmacy', 'صيدلية'), ('restaurant', 'مطعم'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المتجر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المتجر')),
            ],
            options={
                'verbose_name': 'متجر',
                'verbose_name_plural': 'المتاجر',
                'ordering': ['-created_at'],
            },
        ),
    ]
