# Generated by Django 5.2.4 on 2025-07-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_store_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('grocery', 'بقالة'), ('pharmacy', 'صيدلية'), ('restaurant', 'مطعم'), ('sweets', 'حلويات'), ('bakery', 'مخبوزات'), ('services', 'سباكة و كهرباء'), ('produce', 'خضار و فواكه'), ('gifts', 'هدايا'), ('coffee', 'كوفي'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المتجر'),
        ),
    ]
