# Generated by Django 5.2.4 on 2025-07-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='مبلغ التوصيل (ريال)'),
        ),
    ]
