# Generated by Django 5.2.4 on 2025-07-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='customer_delivery_share',
            field=models.PositiveIntegerField(default=100, help_text='قيمة من 0 إلى 100. تحدد كم يتحمل العميل من رسوم التوصيل.', verbose_name='نسبة يتحملها العميل من التوصيل (%)'),
        ),
    ]
