# Generated by Django 5.2.4 on 2025-07-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('customer_location', models.CharField(blank=True, max_length=255, verbose_name='الوصف النصي للموقع')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('details', models.TextField(verbose_name='تفاصيل الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('delivery_type', models.CharField(choices=[('pickup', 'استلام من المحل'), ('delivery', 'توصيل')], max_length=20, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التجهيز'), ('delivering', 'قيد التوصيل'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي'), ('deleted', 'محذوف')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('store', models.ForeignKey(limit_choices_to={'user_type': 'merchant'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('order_details', models.TextField(verbose_name='تفاصيل الطلب')),
                ('order_type', models.CharField(choices=[('pickup', 'استلام من المحل'), ('delivery', 'توصيل')], max_length=20, verbose_name='نوع الطلب')),
                ('location_lat', models.FloatField(verbose_name='خط العرض')),
                ('location_lng', models.FloatField(verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'طلب متجر',
                'verbose_name_plural': 'طلبات المتاجر',
                'ordering': ['-created_at'],
            },
        ),
    ]
