# Generated by Django 5.2.4 on 2025-07-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الفاتورة'),
        ),
    ]
