# Generated by Django 5.2.4 on 2025-07-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='رسوم التوصيل'),
        ),
    ]
